import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import HeaderMobile from "@/components/header-mobile";
import SideNav from "@/components/side-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Algoscope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'bg-white ${inter.className}'}>
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <Header />
            <HeaderMobile />
            {children} 
          </main>
         
        </div>
      </body>
    </html>
  );
}
